server:
  port: 8011
  
spring:  application:    name: microservice-comsumer-movie-ribbon
    
    
eureka:  client:    service-url:      defaultZone: http://localhost:8080/eureka
  instance:    prefer-ip-address: true