version: '3.3' # 表示该docker-compose.yml文件使用的是Version 3.1 文件格式
services:
  eureka-server: # 指定docker容器名称
    image: micro-eureka-server:0.0.1-SNAPSHOT #指定镜像名称，
    container_name: eureka-server
    restart: always
    ports:
      - 8761:8761 # 指定端口映射，类似docker run的-p选项，注意使用字符串形式
      
  peer1:
    image: microservice-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-peer1
    restart: always
    hostname: peer1
    ports:
      - 8761:8761
    environment:
      spring.profiles.active: peer1
      EUREKA_URL: http://peer2:8762/eureka
  peer2:
    image: microservice-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-peer2
    hostname: peer2
    restart: always
    ports:
      - 8762:8762
    environment:
      spring.profiles.active: peer2
      EUREKA_URL: http://peer1:8761/eureka
      
  user-service:
    images: microservice-provider-user:0.0.1-SNAPSHOT
    container_name: user-service
    depends_on: 
      - eureka-server
    links:
      - eureka-server
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
    ports: 
      - 8004:8004
   
  movie-service:
    images: microservice-consume-moive:0.0.1-SNAPSHOT
    container_name: movie-service
    depends_on: 
      - eureka-server
    links:
      - eureka-server
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
    ports: 
      - 8010:8010
      
      
      

